export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
source $ZSH/oh-my-zsh.sh

plugins=(gitfast)

# Run neofetch and display system info
if [ -x "$(command -v neofetch)" ]; then
  neofetch
fi

# disable cursor blinking
echo "\e[2 q"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:$HOME/.local/share/bob/nvim-bin

EXCLUDES=(--exclude .git --exclude node_modules --exclude venv --exclude __pycache__ --exclude snap --exclude .cache)

# Fuzzy find directories in home directory/key paths
fzf_cd_home()
{
    local dir
    dir=$( ( \
        echo "/home/toukka" && \
        fd --type d $EXCLUDES . /home/toukka \
        ) | fzf) && \
        cd "$dir" || return 1
    zle reset-prompt
}
zle -N fzf_cd_home
bindkey '^s' fzf_cd_home

# Fuzzy find directories in current directory
fzf_cd_curr()
{
    local dir
    dir=$( (echo "${PWD}" && fd --type d --hidden $EXCLUDES . "${PWD}") | fzf) && cd "$dir" || return 1
    zle reset-prompt
}
zle -N fzf_cd_curr
bindkey '^t' fzf_cd_curr

# Fuzzy find files in home/key paths
fzf_file_home_cd() {
    local file
    file=$(fd --type f $EXCLUDES . /home/toukka | fzf) || return 1
    if [ -n "$file" ]; then
        cd "$(dirname "$file")"
    fi
    zle reset-prompt
}
zle -N fzf_file_home_cd
bindkey '^g' fzf_file_home_cd

# Fuzzy find files in current dir
fzf_file_curr_cd() {
    local file
    file=$( (echo "${PWD}" && fd --type f --hidden $EXCLUDES . "${PWD}") | fzf) || return 1
    if [ -n "$file" ]; then
        cd "$(dirname "$file")"
    fi
    zle reset-prompt
}
zle -N fzf_file_curr_cd
bindkey '^f' fzf_file_curr_cd

