export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
source $ZSH/oh-my-zsh.sh

plugins=(gitfast)

# Run neofetch and display system info
if [ -x "$(command -v neofetch)" ]; then
  neofetch
fi

# disable cursor blinking
echo "\e[2 q"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

alias fd="fdfind"
# fuzzy find in home directory
fzf_cd_home()
{
    local dir
    dir=$(fd --type d --exclude .git --exclude node_modules --exclude snap . /home/touko/repos /mnt/d/files /home/touko/qrnd | fzf) && cd "$dir" || return 1
    zle reset-prompt  # Refresh the prompt
}
# Convert the function into a Zsh widget
zle -N fzf_cd_home
bindkey '^f' fzf_cd_home

# fuzzy find in current directory
fzf_cd_curr()
{
    local dir
    dir=$(fd --type d --hidden . ${PWD} | fzf) && cd "$dir" || return 1
    zle reset-prompt  # Refresh the prompt
}
# Convert the function into a Zsh widget
zle -N fzf_cd_curr
bindkey '^t' fzf_cd_curr

