export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
source $ZSH/oh-my-zsh.sh

plugins=(gitfast)

# Run neofetch and display system info
if [ -x "$(command -v neofetch)" ]; then
  neofetch
fi

# disable cursor blinking
echo "\e[2 q"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$PATH:/opt/nvim-linux64/bin"

#. "$HOME/.cargo/env"

#alias fd="fdfind"
# fuzzy find in home directory
fzf_cd_home()
{
    local dir
    dir=$(fd --type d --exclude .git --exclude node_modules --exclude snap . /home/toukka | fzf) && cd "$dir" || return 1
    zle reset-prompt  # Refresh the prompt
}
# Convert the function into a Zsh widget
zle -N fzf_cd_home
bindkey '^f' fzf_cd_home

# fuzzy find in current directory
fzf_cd_curr()
{
    local dir
    dir=$(fd --type d --hidden . ${PWD} | fzf) && cd "$dir" || return 1
    zle reset-prompt  # Refresh the prompt
}
# Convert the function into a Zsh widget
zle -N fzf_cd_curr
bindkey '^t' fzf_cd_curr

# Aliases

alias ga='git add'
alias gap='ga --patch'
alias gb='git branch'
alias gba='gb --all'
alias gc='git commit'
alias gca='gc --amend --no-edit'
alias gce='gc --amend'
alias gco='git checkout'
alias gcl='git clone --recursive'
alias gd='git diff --output-indicator-new=" " --output-indicator-old=" "'
alias gds='gd --staged'
alias gi='git init'
alias gl='git log --graph --pretty=format:"%C(magenta)%h %C(white) %an  %ar%C(blue)  %D%n%B%n"'
alias gm='git merge'
alias gn='git checkout -b'  # new branch
alias gp='git push'
alias gr='git reset'
alias gre='git restore'
alias gs='git status --short'
alias gu='git pull'

gri() {
  git rebase -i HEAD~$1
}
